// ! Components and containers
import Head from "next/head";
import NavBar from "../containers/landingPage/NavBar";
import Image from "next/image";

// !images and icons

export default function Home() {
  return (
    <>
      {/* Head Section  */}
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="../assets/favicon.svg" />
      </Head>
      <NavBar />
      {/* Main Content */}
    </>
  );
}
