// ! Components and containers
import Head from "next/head";
import NavBar from "../containers/landingPage/NavBar";
import Image from "next/image";
import { useState } from "react";
import Header from "../containers/landingPage/Header";
import Services from "../containers/landingPage/Services";

// !images and icons

export default function Home() {
  //  ! states used in the page
  const [navActive, setNavActive] = useState({
    home: true,
    blog: false,
    login: false,
  });

  return (
    <>
      {/* Head Section  */}
      <Head>
        <title>dRisk&#8482; | Crypto without losses!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/favicon.ico" />
      </Head>

      {/* Main Content */}
      <div className="landingPage">
        <div className="landingPage__navBar--wrapper">
          <NavBar navActive={navActive} setNavActive={setNavActive} />
        </div>
        <Header />
        <Services />
      </div>
    </>
  );
}
