// ! Components and containers
import Head from "next/head";
import NavBar from "../containers/landingPage/NavBar";
import Image from "next/image";
import { useState } from "react";
import Header from "../containers/landingPage/Header";
import Services from "../containers/landingPage/Services";
import ProductUse from "../containers/landingPage/ProductUse";
import Calculator from "../containers/landingPage/Calculator";
import Vc from "../containers/landingPage/Vc";
import Investors from "../containers/landingPage/Investors";
import Testimonial from "../containers/landingPage/Testimonial";
import Cta from "../containers/landingPage/Cta";
import Footer from "../containers/landingPage/Footer";

// !images and icons

export default function Home() {
  //  ! states used in the page
  const [navActive, setNavActive] = useState({
    home: true,
    blog: false,
    login: false,
  });

  return (
    <>
      {/* Head Section  */}
      <Head>
        <title>dRisk&#8482; | Crypto without losses!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/favicon.ico" />
      </Head>

      {/* Main Content */}
      <div className="landingPage">
        <div className="landingPage__navBar--wrapper">
          <NavBar navActive={navActive} setNavActive={setNavActive} />
        </div>
        <Header />
        <Services />
        <ProductUse />
        <Calculator />
        <Vc />
        <Investors />
        <Testimonial />
        <Cta />
        <Footer />
      </div>
    </>
  );
}
